import { Team } from '@/types/team'

export const team: Team[] = [
  {
    id: 1,
    name: 'Arsenal',
    abbr: 'ARS',
    played: 0,
    won: 0,
    drawn: 0,
    lost: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    points: 0,
    score: 0,
    imageUrl: 'https://resources.premierleague.com/premierleague/badges/50/t3.png'
  },
  {
    id: 2,
    name: 'Aston Villa',
    abbr: 'AVL',
    played: 0,
    won: 0,
    drawn: 0,
    lost: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    points: 0,
    score: 0,
    imageUrl: 'https://resources.premierleague.com/premierleague/badges/50/t7.png'
  },
  {
    id: 3,
    name: 'Bournemouth',
    abbr: 'BOU',
    played: 0,
    won: 0,
    drawn: 0,
    lost: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    points: 0,
    score: 0,
    imageUrl: 'https://resources.premierleague.com/premierleague/badges/50/t91.png'
  },
  {
    id: 4,
    name: 'Brentford',
    abbr: 'BRE',
    played: 0,
    won: 0,
    drawn: 0,
    lost: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    points: 0,
    score: 0,
    imageUrl: 'https://resources.premierleague.com/premierleague/badges/50/t94.png'
  },
  {
    id: 5,
    name: 'Brighton & Hove Albion',
    abbr: 'BHA',
    played: 0,
    won: 0,
    drawn: 0,
    lost: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    points: 0,
    score: 0,
    imageUrl: 'https://resources.premierleague.com/premierleague/badges/50/t36.png'
  },
  {
    id: 6,
    name: 'Burnley',
    abbr: 'BUR',
    played: 0,
    won: 0,
    drawn: 0,
    lost: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    points: 0,
    score: 0,
    imageUrl: 'https://resources.premierleague.com/premierleague/badges/50/t90.png'
  },
  {
    id: 7,
    name: 'Chelsea',
    abbr: 'CHE',
    played: 0,
    won: 0,
    drawn: 0,
    lost: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    points: 0,
    score: 0,
    imageUrl: 'https://resources.premierleague.com/premierleague/badges/50/t8.png'
  },
  {
    id: 8,
    name: 'Crystal Palace',
    abbr: 'CRY',
    played: 0,
    won: 0,
    drawn: 0,
    lost: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    points: 0,
    score: 0,
    imageUrl: 'https://resources.premierleague.com/premierleague/badges/50/t31.png'
  },
  {
    id: 9,
    name: 'Everton',
    abbr: 'EVE',
    played: 0,
    won: 0,
    drawn: 0,
    lost: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    points: 0,
    score: 0,
    imageUrl: 'https://resources.premierleague.com/premierleague/badges/50/t11.png'
  },
  {
    id: 10,
    name: 'Fulham',
    abbr: 'FUL',
    played: 0,
    won: 0,
    drawn: 0,
    lost: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    points: 0,
    score: 0,
    imageUrl: 'https://resources.premierleague.com/premierleague/badges/50/t54.png'
  },
  {
    id: 11,
    name: 'Liverpool',
    abbr: 'LIV',
    played: 0,
    won: 0,
    drawn: 0,
    lost: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    points: 0,
    score: 0,
    imageUrl: 'https://resources.premierleague.com/premierleague/badges/25/t14.png'
  },
  {
    id: 12,
    name: 'Luton Town',
    abbr: 'LUT',
    played: 0,
    won: 0,
    drawn: 0,
    lost: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    points: 0,
    score: 0,
    imageUrl: 'https://resources.premierleague.com/premierleague/badges/50/t102.png'
  },
  {
    id: 13,
    name: 'Manchester City',
    abbr: 'MCI',
    played: 0,
    won: 0,
    drawn: 0,
    lost: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    points: 0,
    score: 0,
    imageUrl: 'https://resources.premierleague.com/premierleague/badges/50/t43.png'
  },
  {
    id: 14,
    name: 'Manchester United',
    abbr: 'MUN',
    played: 0,
    won: 0,
    drawn: 0,
    lost: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    points: 0,
    score: 0,
    imageUrl: 'https://resources.premierleague.com/premierleague/badges/50/t1.png'
  },
  {
    id: 15,
    name: 'Newcastle United',
    abbr: 'NEW',
    played: 0,
    won: 0,
    drawn: 0,
    lost: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    points: 0,
    score: 0,
    imageUrl: 'https://resources.premierleague.com/premierleague/badges/50/t4.png'
  },
  {
    id: 16,
    name: 'Nottingham Forest',
    abbr: 'NFO',
    played: 0,
    won: 0,
    drawn: 0,
    lost: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    points: 0,
    score: 0,
    imageUrl: 'https://resources.premierleague.com/premierleague/badges/50/t17.png'
  },
  {
    id: 17,
    name: 'Sheffield United',
    abbr: 'SHU',
    played: 0,
    won: 0,
    drawn: 0,
    lost: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    points: 0,
    score: 0,
    imageUrl: 'https://resources.premierleague.com/premierleague/badges/50/t49.png'
  },
  {
    id: 18,
    name: 'Tottenham Hotspur',
    abbr: 'TOT',
    played: 0,
    won: 0,
    drawn: 0,
    lost: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    points: 0,
    score: 0,
    imageUrl: 'https://resources.premierleague.com/premierleague/badges/50/t6.png'
  },
  {
    id: 19,
    name: 'West Ham United',
    abbr: 'WHU',
    played: 0,
    won: 0,
    drawn: 0,
    lost: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    points: 0,
    score: 0,
    imageUrl: 'https://resources.premierleague.com/premierleague/badges/50/t21.png'
  },
  {
    id: 20,
    name: 'Wolverhampton Wanderers',
    abbr: 'WOL',
    played: 0,
    won: 0,
    drawn: 0,
    lost: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    points: 0,
    score: 0,
    imageUrl: 'https://resources.premierleague.com/premierleague/badges/50/t39.png'
  },
]
