name: Vercel Production Deployment
env:
 VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
 VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
 push:
  branches:
   - main
jobs:
 Deploy-Production:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - uses: actions/setup-node@v3
        with:
          node-version: '18'  # Or a suitable Node.js version
          cache: 'pnpm' 
   - name: Install pnpm
    if: steps.cache.outputs.cache-hit != 'true' # Install only if not cached
    run: npm install -g pnpm
   - name: Install Dependencies
    run: pnpm install 
   - name: Pull Vercel Environment Information
    run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
   - name: Build Project Artifacts
    run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
   - name: Deploy Project Artifacts to Vercel
    run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
